services:
  web:
    build: .
    container_name: marotto-solutions
    restart: always
    ports:
      - "${APP_PORT:-3081}:3000"
      # environment:
      # - NEXT_TELEMETRY_DISABLED=1
      # Add WebDAV env vars here later
    volumes:
      - ./public:/app/public
      - marotto_data:/app/data
      # - ./.next:/app/.next # Careful with syncing .next in dev

volumes:
  marotto_data:
